name: Trivy Container Scan

description: Scan container image for vulnerabilities

runs:
  using: composite

  steps:

    - name: Scan Image
      shell: bash
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy image \
          --severity CRITICAL \
          --exit-code 1 \
          app:${GITHUB_SHA}
