name: Java Quality

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string

jobs:

  quality:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: Rajkumar06706/java-github/actions/setup-java@main
        with:
          java-version: ${{ inputs.java-version }}

      - name: Compile
        uses: Rajkumar06706/java-github/actions/compile@main

      - name: Unit Test
        uses: Rajkumar06706/java-github/actions/unit-test@main

      - name: JaCoCo
        uses: Rajkumar06706/java-github/actions/jacoco@main

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Spotless
        uses: Rajkumar06706/java-github/actions/spotless@main

      - name: SpotBugs
        uses: Rajkumar06706/java-github/actions/spotbugs@main
