name: Platform CI

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
    secrets:
      GITOPS_TOKEN:
        required: true

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  actions: read
  security-events: write
  
env:
  REGISTRY: ghcr.io

jobs:

  ci:

    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.image.outputs.image-uri }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Verify GAR Authentication
        run: |
          gcloud auth print-access-token | head -c 20
          echo ""

      #- name: Verify GCP Access
      #  run: |
       #   gcloud artifacts repositories describe platform-images \
        #    --location=asia-southeast1
  
      - name: Setup Java
        uses: Rajkumar06706/java-github/actions/setup-java@main
        with:
          java-version: ${{ inputs.java-version }}

      - name: Build
        uses: Rajkumar06706/java-github/actions/compile@main

      - name: Unit Test
        uses: Rajkumar06706/java-github/actions/unit-test@main

      - name: Package
        uses: Rajkumar06706/java-github/actions/package-jar@main

      - name: Generate SBOM
        uses: Rajkumar06706/java-github/actions/generate-sbom@main

      - name: Build Container
        uses: Rajkumar06706/java-github/actions/build-container@main

      - name: Image Metadata
        id: image
        uses: Rajkumar06706/java-github/actions/image-metadata@main
        with:
          image-prefix: asia-southeast1-docker.pkg.dev/mimetic-retina-419011/platform-images/${{ github.event.repository.name }}

      - name: Trivy Scan
        uses: Rajkumar06706/java-github/actions/trivy-scan@main

      - name: Push Image
        uses: Rajkumar06706/java-github/actions/push-image@main
        with:
          image-uri: ${{ steps.image.outputs.image-uri }}

  deploy-dev:

    needs: ci
  
    uses: Rajkumar06706/java-github/.github/workflows/platform-cd.yml@main
  
    with:
      image-uri: ${{ needs.ci.outputs.image-uri }}
  
    secrets:
      gitops-token: ${{ secrets.GITOPS_TOKEN }}

